---

- hosts: homegroup
  become: yes
  gather_facts: no
  tasks: 

  - name: install updates
    apt: 
      upgrade: dist
      state: latest
      update_cache: yes
    

  - name: git & pip install
    apt:
      name: 
        - git
        - python3-pip
        - python3-venv
        - ufw
      state: latest
      update_cache: yes

  - git:
      repo: "{{git_repo}}"
      dest: "{{project_path}}"
      update: no


  - name: install flask
    pip:
      name: flask

  - name: limiting ports
    ufw: 
      policy: deny

  - name: opening ports
    ufw:
      rule: allow
      name: OpenSSH

  - name: opening ports2
    ufw:
      rule: allow
      name: WWW Full


  - name: enable ufw
    ufw: 
      state: enabled      

 

  # - name: launch app
  #   shell: cd "{{project_path}}/Task2" && sudo nohup python3 -u main.py > output.log &




