---

- hosts: homegroup
  become: yes
  gather_facts: no
  tasks: 

  # - name: install updates
  #   apt: 
  #     upgrade: dist
  #     state: latest
  #     update_cache: yes
    

  # - name: git & pip install
  #   apt:
  #     name: 
  #       - git
  #       - python3-pip
  #       - python3-venv
  #       - ufw
  #     state: latest
  #     update_cache: yes

  # - name: remove python < 3
  #   apt:
  #     name: python2.7-minimal
  #     state: absent 
  #     purge: yes    

  - git:
      repo: "{{git_repo}}"
      dest: "{{project_path}}"
      update: no


  # - name: install pip packets
  #   pip:
  #     name: 
  #       - flask
  #       - emoji
  #       - pyOpenSSL

  #     state: latest

  # - name: limiting ports
  #   ufw: 
  #     policy: deny

  # - name: opening ports
  #   ufw:
  #     rule: allow
  #     name: OpenSSH

  # - name: opening ports2
  #   ufw:
  #     rule: allow
  #     name: WWW Full


  # - name: enable ufw
  #   ufw: 
  #     state: enabled      

 

  - name: launch app
    shell: cd "{{project_path}}/Task2" && sudo nohup python3 -u main.py > flasklog.log &
    register: tmppython

  - name: Get stdout or stderr from the output
    debug:
      var: tmppython.stdout




