- hosts: homegroup
  become: yes
  gather_facts: no
  tasks: 
  
  - name: generate service file from template 
    template:
      src: test_service.j2
      dest: /etc/systemd/system/test.service  

  - name: prepare service 
    systemd: 
      name: test
      daemon-reload: yes
      enabled: yes

