- hosts: homegroup
  become: yes
  gather_facts: yes
  tasks: 

  # - name: Set authorized key taken from file
  #   authorized_key:
  #     user: "{{ansible_user}}"
  #     state: present
  #     manage_dir: yes
  #     key: "{{lookup('file','jay.pub')}}"
  
  # - name: generate service file from template 
  #   template:
  #     src: test_service.j2
  #     dest: /etc/systemd/system/test.service  

  # - name: prepare service 
  #   systemd: 
  #     name: test
  #     daemon-reload: yes
  #     enabled: yes


  # - replace:
  #     path: '/etc/ssh/sshd_config'
  #     after: 'PasswordAuthentication'
  #     regexp: '^(.*)PasswordAuthentication(.*)$'
  #     replace: ''

  # - name: Disable root SSH login
  #   lineinfile:
  #     dest: /etc/ssh/sshd_config
  #     regexp: "^PermitRootLogin"
  #     line: "PermitRootLogin no"
  #     state: present    

  # - lineinfile:
  #     path: '/etc/ssh/sshd_config'
  #     regexp: '^(.*)PasswordAuthentication(.*)$'
  #     line: 'PasswordAuthentication no'      

  # - name: restarting service
  #   service:
  #     name: sshd
  #     state: restarted



  - name: rewriting hosts
    lineinfile:
      dest: /etc/hosts
      insertbefore: BOF
      line: "localhost {{ansible_hostname}}.localhost"
      state: present





