- hosts: homegroup
  become: yes
  gather_facts: yes

  # vars: 
  #   ssh_key_filename: Elvira_T

  # tasks: 
  #   - name: Create a directory if it does not exist
  #     file:
  #       path: ~/.ssh
  #       state: directory

  #   - name: generate SSH key "{{ssh_key_filename}}"
  #     openssh_keypair:
  #       path: "~/.ssh/{{ssh_key_filename}}"
  #       type: rsa
  #       size: 4096
  #       state: present
  #       force: no


